### PR TITLE
Added preprocessing description

### PR DESCRIPTION
**Pull request by bpickett**
Moved global virus response directory to subdirectory within project1

### CODE REVIEW

**Comment by bpickett** [comment]
This is the workflow that was used on all 3 virus datasets to generate not just DE lists, but functions, pathways, etc.

We are hoping to compare the results from each pipeline.

**Comment by bpickett** [comment]
@avantikalal : please see above comment. Thanks!

**Comment by avantikalal** [comment]
Hi @bpickett , thanks for explaining. Could you just put a sentence to explain that in the README file itself, and I'll merge it.

**Comment by bpickett** [comment]
@avantikalal for your review.

**Pull request merged**
