### PR TITLE
TEtools

### PR DESCRIPTION
**Pull request by edawson**
This adds a TEtools dockerfile, though it requires a special command line invocation. While @uniqueg is working on sorting that out, the current one will work.

### CODE REVIEW

**Comment by uniqueg** [comment]
Actually the rebuild is just for cosmetics and slightly reduced image size. It should already work as intended, hopefully :) All scripts are executable and available in the `$PATH`, so you can do something like:

```bash
docker run --rm -it zavolab/tetools:1.0.0 TEcount.py --help
```

More info here: https://github.com/l-modolo/TEtools

**Comment by uniqueg** [comment]
Might be good to add links to the Dockerfiles in case someone wants to adapt them. I will open an issue for that.

**Comment by uniqueg** [comment]
@edawson

To render the list of tools in table format you can use:

```console
| Tool | Image |
| --- | --- |
| [Bowtie2](http://bowtie-bio.sourceforge.net/bowtie2/index.shtml) | [quay.io/biocontainers/bowtie2:2.4.1--py38he513fc3_0](quay.io/biocontainers/bowtie2:2.4.1--py38he513fc3_0) ([Dockerfile]()) |
| [FastQC](https://github.com/s-andrews/FastQC) | [quay.io/biocontainers/fastqc:0.11.5--1](quay.io/biocontainers/fastqc:0.11.5--1) ([Dockerfile]()) |
| [Fastq-screen](https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/) | [quay.io/biocontainers/fastq-screen:0.11.3--pl5.22.0_0](quay.io/biocontainers/fastq-screen:0.11.3--pl5.22.0_0) ([Dockerfile]()) |
| [featureCounts](http://subread.sourceforge.net) | [hpobiolab/feature-count](hpobiolab/feature-counts) ([Dockerfile]()) |
| [HISAT2](https://daehwankimlab.github.io/hisat2/) | [quay.io/biocontainers/hisat2:2.2.0--py37he1b5a44_0](quay.io/biocontainers/hisat2:2.2.0--py37he1b5a44_0) ([Dockerfile]()) |
| [KissSplice](http://kissplice.prabi.fr/) | [hpobiolab/kiss-splice](hpobiolab/kiss-splice) ([Dockerfile]()) |
| [LIONS](https://github.com/ababaian/LIONS) | [hpobiolab/lions](hpobiolab/lions) ([Dockerfile]()) |
| [MultiQC](https://github.com/ewels/MultiQC) | [quay.io/biocontainers/multiqc:1.8--py_2](quay.io/biocontainers/multiqc:1.8--py_2) ([Dockerfile]()) |
| [picard](https://broadinstitute.github.io/picard/) | [quay.io/biocontainers/picard:2.22.2--0](quay.io/biocontainers/picard:2.22.2--0) ([Dockerfile]()) |
| [samtools](https://github.com/samtools/samtools) | [quay.io/biocontainers/picard:2.22.2--0](quay.io/biocontainers/picard:2.22.2--0) ([Dockerfile]()) |
| [STAR](https://github.com/alexdobin/STAR) | [quay.io/biocontainers/star:2.7.3a--0](quay.io/biocontainers/star:2.7.3a--0) ([Dockerfile]()) |
| [TEtools](https://github.com/l-modolo/TEtools) | [zavolab/tetools:1.0.0](zavolab/tetools:1.0.0) ([Dockerfile](https://github.com/zavolanlab/Dockerfiles/blob/master/TEtools/1.0.0/Dockerfile)) |
| [TEtranscripts](http://hammelllab.labsites.cshl.edu/software) | [quay.io/biocontainers/tetranscripts:2.1.4--py_0](quay.io/biocontainers/tetranscripts:2.1.4--py_0) ([Dockerfile]()) |
| [trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic) | [quay.io/biocontainers/trimmomatic:0.33--1](quay.io/biocontainers/trimmomatic:0.33--1) ([Dockerfile]()) |
```

Should look like this:

| Tool | Image |
| --- | --- |
| [Bowtie2](http://bowtie-bio.sourceforge.net/bowtie2/index.shtml) | [quay.io/biocontainers/bowtie2:2.4.1--py38he513fc3_0](quay.io/biocontainers/bowtie2:2.4.1--py38he513fc3_0) ([Dockerfile]()) |
| [FastQC](https://github.com/s-andrews/FastQC) | [quay.io/biocontainers/fastqc:0.11.5--1](quay.io/biocontainers/fastqc:0.11.5--1) ([Dockerfile]()) |
| [Fastq-screen](https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/) | [quay.io/biocontainers/fastq-screen:0.11.3--pl5.22.0_0](quay.io/biocontainers/fastq-screen:0.11.3--pl5.22.0_0) ([Dockerfile]()) |
| [featureCounts](http://subread.sourceforge.net) | [hpobiolab/feature-count](hpobiolab/feature-counts) ([Dockerfile]()) |
| [HISAT2](https://daehwankimlab.github.io/hisat2/) | [quay.io/biocontainers/hisat2:2.2.0--py37he1b5a44_0](quay.io/biocontainers/hisat2:2.2.0--py37he1b5a44_0) ([Dockerfile]()) |
| [KissSplice](http://kissplice.prabi.fr/) | [hpobiolab/kiss-splice](hpobiolab/kiss-splice) ([Dockerfile]()) |
| [LIONS](https://github.com/ababaian/LIONS) | [hpobiolab/lions](hpobiolab/lions) ([Dockerfile]()) |
| [MultiQC](https://github.com/ewels/MultiQC) | [quay.io/biocontainers/multiqc:1.8--py_2](quay.io/biocontainers/multiqc:1.8--py_2) ([Dockerfile]()) |
| [picard](https://broadinstitute.github.io/picard/) | [quay.io/biocontainers/picard:2.22.2--0](quay.io/biocontainers/picard:2.22.2--0) ([Dockerfile]()) |
| [samtools](https://github.com/samtools/samtools) | [quay.io/biocontainers/picard:2.22.2--0](quay.io/biocontainers/picard:2.22.2--0) ([Dockerfile]()) |
| [STAR](https://github.com/alexdobin/STAR) | [quay.io/biocontainers/star:2.7.3a--0](quay.io/biocontainers/star:2.7.3a--0) ([Dockerfile]()) |
| [TEtools](https://github.com/l-modolo/TEtools) | [zavolab/tetools:1.0.0](zavolab/tetools:1.0.0) ([Dockerfile](https://github.com/zavolanlab/Dockerfiles/blob/master/TEtools/1.0.0/Dockerfile)) |
| [TEtranscripts](http://hammelllab.labsites.cshl.edu/software) | [quay.io/biocontainers/tetranscripts:2.1.4--py_0](quay.io/biocontainers/tetranscripts:2.1.4--py_0) ([Dockerfile]()) |
| [trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic) | [quay.io/biocontainers/trimmomatic:0.33--1](quay.io/biocontainers/trimmomatic:0.33--1) ([Dockerfile]()) |

Dockerfile links are still empty (except for TEtools)

**Comment by avantikalal** [comment]
@edawson can you incorporate the links to the dockerfiles as suggested by @uniqueg ?

**Comment by edawson** [comment]
Yep, I'll put them in table format. I'll see if I can get Dockerfiles for images pulled from BioContainers!

**Pull request merged**
